### PR TITLE
use latest versions of the dependencies (auto)

### PR DESCRIPTION
**Pull request by larziwau**

### CODE REVIEW

**Comment by larziwau** [comment]
Well the * makes Rust use the latest versions of the libraries (jst found abt it)

if its gonna break things so often, i can update them by hand.

**Comment by dankmeme01** [comment]
please revert the `*` change, it's not a good idea and will likely cause things to break randomly every once in a while.

in general, while making prs to update dependencies is ok, i'm not sure what's the point. unless there's a major security/performance issue, I don't see what gain there is

**Comment by larziwau** [comment]
well youre right aswell

**Comment by larziwau** [comment]
ill update them manually today

**Pull request closed without merging**
