### PR TITLE
Update server CI, dependencies and change to Rust 2024 edition

### PR DESCRIPTION
**Pull request by larziwau**
Well Ive also switched to a new rust gh action bc the old one was unmaintained

### CODE REVIEW

**Comment by larziwau** [comment]
Update tons of libraries, + fix code errors

**Comment by dankmeme01** [comment]
i appreciate the effort but you didn't have to bump edition to 2024 and bump all dependencies, i can see you slowly trying to fix everything through action builds but it'll be simpler if i did that myself locally :sob: 

some of the attempts to fix warnings/errors aren't done correctly and will lead to issues as well

**Comment by larziwau** [comment]
> i appreciate the effort but you didn't have to bump edition to 2024 and bump all dependencies, i can see you slowly trying to fix everything through action builds but it'll be simpler if i did that myself locally 😭
> 
> some of the attempts to fix warnings/errors aren't done correctly and will lead to issues as well

ur so right lol, im looking at the all of the actions to fix them manually, also updated the deps to make them more futureproof lol, a help would be great tho

**Comment by dankmeme01** [comment]
alright

**Comment by larziwau** [comment]
@dankmeme01 also btw hear me out and NEVER UPDATE sqlx at what cost. it errors about sql3. it took me 30 mins to to figure out i have to downgrade that.

**Comment by larziwau** [comment]
also i think we should set up a linter (sorry but ur formatting sucks 😭 )

**Comment by dankmeme01** [comment]
> @dankmeme01 also btw hear me out and NEVER UPDATE sqlx at what cost. it errors about sql3. it took me 30 mins to to figure out i have to downgrade that.

oh yeah i've ran into that as well, it seems that `rocket_db_pools` depends strictly on sqlx `^0.7.0` and if we update our sqlx to `0.8.x` they enter a conflict. not really sure what we can do until rocket updates their dependency


> also i think we should set up a linter (sorry but ur formatting sucks 😭 )

aw :( is it about client or server? server uses `rustfmt` which i sometimes kinda dislike but it's been mostly fine for me, and for client i don't really want to use clang-format, i like my own code style

**Comment by larziwau** [comment]
well yeah but both the mod itself and server formatting is a bit bad. i will try to figure linter thing out sometime

**Pull request merged**
